### ISSUE TITLE
Way to automatically delete spam emails inside the trash forever in Gmail like fake PayPal emails

### ISSUE THREAD

**Issue by R2MGaming** [mmartial/gmail-spam-cleaner#1]
I tried this last night to get rid of all spam emails without having to delete them forever manually inside my trash bin on my Gmail, and it seems to work with most spam emails except for "fake PayPal" emails that appeared in my Gmail's trash label this morning and I tried running the script to remove them and it didn't remove these spam emails from my trash permanently so is there a way to have this auto-delete these fake PayPal emails from my Gmail trash?

**Comment by R2MGaming** [comment]
On second thought, when I try cleaning the spam folder, it gives me a reference error saying "mid_domains is not defined".

**Comment by mmartial** [comment]
It is hard to answer your question specifically: the entire script acts as a set of custom filters you manually enable to clean up your spam and push the content into those "autodeleted" labels as the script runs. The trick is to find what characterizes that particular sender and add it to one of the filter functions: From, Message-ID, ...

I often ran the script manually to test it. There is a `debug` flag (see line 34) that you can enable to do manual runs and see what the tool sees/look for. It might help you understand what is at fault.

As for the `mid_domains` it is defined on line 70. Create an empty one if you are not using that filter.

**Comment by R2MGaming** [comment]
Thank you for the response. I honestly never knew how to debug the Google Script of course.
